### PR TITLE
test: cleanup test package;

### LINKED ISSUE #27: Fix integration test batch processing
Given i do a `go test -tags integration ./...`, i get failures.
I believe these are due to the docker containers being still removed while the next integration test is already running and then compaining about that process:
```
go test -tags integration ./...
go: finding github.com/applike/gosoline v0.0.24
...
dynamodb component of type dynamodb is ready
could not start gosoline_test_mysql container
: container already exists
FAIL    test1    44.724s
ok      test2   59.378s
could not remove existing gosoline_test_dynamoDb container
Error while removing container with name gosoline_test_dynamoDb: API error (409): removal of container 6fc236688d90bc79d58a632dc6b1bcd7d2e7dfbd09ddc25f1e67181073751c2d is already in progress
FAIL    test3      1.067s
```

### PR DESCRIPTION
**Pull request by josketres**
**Summary:**

- Use `pkg/cfg` for configuration.
- Removed all global variables. (less 🍝 )
- Tests can now be executed in parallel (if there are no port conflicts).
- Refactored code and separated concerns: all docker stuff in one struct, all sync stuff in another, and so on...

**Package public api:**

image

**Next steps:**

* Find a way to run using dynamic ports so that we avoid port conflicts. And then we can run the tests in parallel and save execution time.

Closes #27

### CODE REVIEW

File: pkg/test/component_wiremock.go [hunk 1]
```diff
@@ -42,15 +51,19 @@ func doRunWiremock(name string, configMap configInput) {
 		},
 	})
 
-	jsonStr, err := ioutil.ReadFile(config.Mocks)
+	jsonStr, err := ioutil.ReadFile(w.settings.Mocks)
 
 	if err != nil {
-		logErr(err, "could not read http mock configuration")
+		panic(fmt.Errorf("could not read http mock configuration : %w", err))
```
Comment (applike-ss) [inline pkg/test/component_wiremock.go]: please remove spaces before colons :)

File: pkg/test/docker.go [hunk 2]
```diff
@@ -1,31 +1,58 @@
...
 	OnDestroy    func()
 	PrintLogs    bool
 }
 
-func runContainer(name string, config ContainerConfig) {
-	err := dockerPool.RemoveContainerByName(name)
+type dockerRunner struct {
+	pool           *dockertest.Pool
+	resources      []*dockertest.Resource
+	resourcesMutex sync.Mutex
```
Comment (applike-ss) [inline pkg/test/docker.go]: i think we usually just call it lock

File: pkg/test/test.go [hunk 3]
```diff
@@ -2,98 +2,121 @@ package test
...
+
+func (t *Mocks) Boot(config cfg.Config) {
+	t.bootFromConfig(config)
 
-	wait.Wait()
+	t.waitGroup.Wait()
 
 	log.Println("test environment up and running")
-	fmt.Println()
+	log.Println()
```
Comment (applike-ss) [inline pkg/test/test.go]: i think there is no point in keeping an empty println

File: pkg/test/test.go [hunk 4]
```diff
@@ -2,98 +2,121 @@ package test
...
-func Shutdown() {
-	for _, res := range dockerResources {
-		if err := dockerPool.Purge(res); err != nil {
-			log.Fatalf("Could not purge resource: %s", err)
-		}
+func (t *Mocks) runComponent(component mockComponent) {
+	t.waitGroup.Add(1)
+	go func() {
+		defer t.waitGroup.Done()
+		component.Run(t.dockerRunner)
```
Comment (applike-ss) [inline pkg/test/test.go]: would it make more sense to call it start? from the wording i would assume that the component is stopped after the "Run".

File: pkg/test/test.go [hunk 5]
```diff
@@ -2,98 +2,121 @@ package test
...
+	return component.ProvideClient(clientType)
+}
+
+func (t *Mocks) Shutdown() {
+	t.dockerRunner.PurgeAllResources()
+}
+
+func Boot(configFilenames ...string) *Mocks {
+	if len(configFilenames) == 0 {
+		configFilenames = append(configFilenames, "config.test.yml")
```
Comment (applike-ss) [inline pkg/test/test.go]: should we rather prepend config.test.yml? Then a user of the component can still decide to override the debug flag for a component for example

File: test/component_cloudwatch_test.go [hunk 6]
```diff
@@ -12,10 +12,10 @@ import (
 func Test_cloudwatch(t *testing.T) {
 	setup(t)
 
-	pkgTest.Boot("test_configs/config.cloudwatch.test.yml")
-	defer pkgTest.Shutdown()
+	mocks := pkgTest.Boot("test_configs/config.cloudwatch.test.yml")
+	defer mocks.Shutdown()
 
-	cwClient := pkgTest.ProvideCloudwatchClient("cloudwatch")
+	cwClient := mocks.ProvideClient("cloudwatch", "cloudwatch").(*cloudwatch.CloudWatch)
```
Comment (applike-ss) [inline test/component_cloudwatch_test.go]: maybe we should rather have some constants for the component type

File: test/fixtures_mysql_test.go [hunk 7]
```diff
@@ -3,13 +3,13 @@
 package test_test
 
 import (
-	"context"
-	"github.com/applike/gosoline/pkg/cfg"
+	"database/sql"
 	db_repo "github.com/applike/gosoline/pkg/db-repo"
```
Comment (applike-ss) [inline test/fixtures_mysql_test.go]: please remove all db_repo aliases in the test pkg :+1:

Comment (josketres) [reply test/fixtures_mysql_test.go]: ✅

File: pkg/test/aws_session.go [hunk 8]
```diff
@@ -11,16 +11,21 @@ import (
...
 
-var sessions = simpleCache{}
+var (
+	awsSessions   simpleCache
+	awsHttpClient *http.Client
+)
 
-var httpClient = &http.Client{
-	Timeout: time.Minute,
+func init() {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/aws_session.go]: In this case, we need global variables.

We can initialize them in the declaration instead of using the init() function. 

I'll do that.

✅

File: pkg/test/component_cloudwatch.go [hunk 9]
```diff
@@ -2,61 +2,63 @@ package test
...
-	defer log.Printf("%s component of type %s is ready", name, "cloudwatch")
-
-	localConfig := &cloudwatchConfig{}
-	unmarshalConfig(configMap, localConfig)
-	cloudwatchConfigs[name] = localConfig
+func (m *cloudwatchComponent) Run(runner *dockerRunner) {
+	defer log.Printf("%s component of type %s is ready", m.name, "cloudwatch")
 
-	containerName := fmt.Sprintf("gosoline_test_cloudwatch_%s", name)
+	containerName := fmt.Sprintf("gosoline_test_cloudwatch_%s", m.name)
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: Good idea.

✅

**Comment by applike-ss** [comment]
this could solve #27

File: pkg/test/component_dynamodb.go [hunk 10]
```diff
@@ -2,73 +2,66 @@ package test
...
-func doRunDynamoDb(name string, configMap configInput) {
-	defer wait.Done()
-	defer log.Printf("%s component of type %s is ready", name, "dynamodb")
-
-	config := &dynamoDbConfig{}
-	unmarshalConfig(configMap, config)
-	dynamoDbConfigs[name] = config
-
-	runDynamoDbContainer(name, config.Debug)
+func (m *dynamoDbComponent) Boot(name string, config cfg.Config, settings *mockSettings) {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_dynamodb.go]: ✅

File: pkg/test/component_cloudwatch.go [hunk 11]
```diff
@@ -2,61 +2,63 @@ package test
...
+		HealthCheck: localstackHealthCheck(runner, containerName),
+		PrintLogs:   m.settings.Debug,
 	})
 }
+
+func (m *cloudwatchComponent) ProvideClient(string) interface{} {
+	return m.provideCloudwatchClient()
+}
+
+func (m *cloudwatchComponent) provideCloudwatchClient() *cloudwatch.CloudWatch {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: ✅

File: pkg/test/component_cloudwatch.go [hunk 12]
```diff
@@ -2,61 +2,63 @@ package test
...
+	return m.clients.New("cloudwatch", func() interface{} {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: ✅

File: pkg/test/test.go [hunk 13]
```diff
@@ -2,98 +2,121 @@ package test
...
-var cfgFilename = "config.test.yml"
-
-func init() {
-	dockerPool, err = dockertest.NewPool("")
-	dockerPool.MaxWait = 2 * time.Minute
-	dockerResources = make([]*dockertest.Resource, 0)
+type mockComponent interface {
+	Boot(name string, config cfg.Config, settings *mockSettings)
+	Run(runner *dockerRunner)
+	ProvideClient(clientType string) interface{}
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/test.go [hunk 14]
```diff
@@ -2,98 +2,121 @@ package test
...
-var configs []*ContainerConfig
-var cfgFilename = "config.test.yml"
-
-func init() {
-	dockerPool, err = dockertest.NewPool("")
-	dockerPool.MaxWait = 2 * time.Minute
-	dockerResources = make([]*dockertest.Resource, 0)
+type mockComponent interface {
+	Boot(name string, config cfg.Config, settings *mockSettings)
+	Run(runner *dockerRunner)
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/test.go [hunk 15]
```diff
@@ -2,98 +2,121 @@ package test
...
+	ProvideClient(clientType string) interface{}
+}
 
-	if err != nil {
-		log.Fatalf("Could not connect to docker: %s", err)
-	}
+type mockSettings struct {
+	Debug     bool   `cfg:"debug"`
+	Component string `cfg:"component"`
+	Host      string `cfg:"host"`
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/test.go]: I will leave it like that for now. 
The problem is the sqs_sns component.
Let's review this another time.

[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/test.go [hunk 16]
```diff
@@ -2,98 +2,121 @@ package test
...
-var dockerResources []*dockertest.Resource
-var configs []*ContainerConfig
-var cfgFilename = "config.test.yml"
-
-func init() {
-	dockerPool, err = dockertest.NewPool("")
-	dockerPool.MaxWait = 2 * time.Minute
-	dockerResources = make([]*dockertest.Resource, 0)
+type mockComponent interface {
+	Boot(name string, config cfg.Config, settings *mockSettings)
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/component_wiremock.go (hunk 1 above)
Comment (josketres) [reply pkg/test/component_wiremock.go]: ✅

File: pkg/test/test.go (hunk 4 above)
Comment (josketres) [reply pkg/test/test.go]: ✅

File: test/component_cloudwatch_test.go (hunk 6 above)
Comment (josketres) [reply test/component_cloudwatch_test.go]: Constants would not help here, because we need to use here the name of your mock.
You can call your mock whatever you want. It is the key of the mocks map in the configuration file.

Comment (josketres) [reply test/component_cloudwatch_test.go]: ✅

File: pkg/test/test.go (hunk 3 above)
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/test.go (hunk 5 above)
Comment (josketres) [reply pkg/test/test.go]: The code here is misleading.
We are not appending anything, we are using a default singleton slice.
```go
	if len(configFilenames) == 0 {
		configFilenames = []string{"config.test.yml"}
	}
```

Comment (josketres) [reply pkg/test/test.go]: ✅

File: go.mod [hunk 17]
```diff
@@ -53,6 +53,7 @@ require (
 	github.com/opencontainers/runc v0.1.1 // indirect
 	github.com/ory/dockertest v3.3.4+incompatible
 	github.com/ory/ladon v1.0.1
+	github.com/pborman/uuid v1.2.0
```
Comment (applike-ss) [inline go.mod]: another uuid lib? Can we reuse the one from twinj?

Comment (applike-ss) [reply go.mod]: should we add a cleanup ticket? with this one we have 5(!) uuid libraries within gosoline

File: test/component_cloudwatch_test.go (hunk 6 above)
Comment (applike-ss) [reply test/component_cloudwatch_test.go]: i got that however, we pass "cloudwatch" twice. One time for the component, which i would replace by the constant and one time as a name for the test component which could just stay as-is

File: test/component_cloudwatch_test.go [hunk 18]
```diff
@@ -12,10 +12,10 @@ import (
 func Test_cloudwatch(t *testing.T) {
 	setup(t)
 
-	pkgTest.Boot("test_configs/config.cloudwatch.test.yml")
-	defer pkgTest.Shutdown()
+	mocks := pkgTest.Boot("test_configs/config.cloudwatch.test.yml")
+	defer mocks.Shutdown()
 
-	cwClient := pkgTest.ProvideCloudwatchClient("cloudwatch")
+	cwClient := mocks.ProvideClients("cloudwatch").CloudWatch
```
Comment (applike-ss) [inline test/component_cloudwatch_test.go]: This implementation looks strange. I liked the prior implementation more. As said: assertions are not a bad thing

File: pkg/test/component_cloudwatch.go [hunk 19]
```diff
@@ -2,61 +2,64 @@ package test
...
-	defer wait.Done()
-	defer log.Printf("%s component of type %s is ready", name, "cloudwatch")
-
-	localConfig := &cloudwatchConfig{}
-	unmarshalConfig(configMap, localConfig)
-	cloudwatchConfigs[name] = localConfig
-
-	containerName := fmt.Sprintf("gosoline_test_cloudwatch_%s", name)
+func (c *cloudwatchComponent) Start() {
+	containerName := fmt.Sprintf("gosoline_test_cloudwatch_%s", c.name)
```
Comment (applike-ss) [inline pkg/test/component_cloudwatch.go]: so we are not adding the job id into the name?

File: go.mod (hunk 17 above)
Comment (j4k4) [reply go.mod]: yes, plz! can we use our own gosoline uuid wrapper? Get rid of all the other usages?

File: pkg/test/component_cloudwatch.go [hunk 20]
```diff
@@ -2,61 +2,64 @@ package test
...
-		}
-
-		return cloudwatch.New(sess)
-	}).(*cloudwatch.CloudWatch)
-}
-
-func runCloudwatch(name string, config configInput) {
-	wait.Add(1)
-	go doRunCloudwatch(name, config)
+func (c *cloudwatchComponent) Boot(config cfg.Config, name string, settings *mockSettings, runner *dockerRunner) {
```
Comment (applike-ss) [inline pkg/test/component_cloudwatch.go]: as said: please order structs before before simple types

File: pkg/test/component_kinesis.go [hunk 21]
```diff
@@ -2,63 +2,66 @@ package test
...
+	}
+}
+
+func (k *kinesisComponent) provideKinesisClient() *kinesis.Kinesis {
+	return k.clients.New(k.name, func() interface{} {
+
+		sess, err := getAwsSession(k.settings.Host, k.settings.Port)
+
+		if err != nil {
+			panic(fmt.Errorf("could not create kinesis client %s: %w", k.name, err))
```
Comment (applike-ss) [inline pkg/test/component_kinesis.go]: in fact we couldn't create a aws session, no?

File: go.mod (hunk 17 above)
Comment (josketres) [reply go.mod]: This was a typo. I'll revert the changes in this file.

File: pkg/test/component_sns_sqs.go [hunk 22]
```diff
@@ -2,131 +2,95 @@ package test
...
 	"strings"
-	"time"
 )
 
-type snsSqsConfig struct {
-	Debug   bool   `mapstructure:"debug"`
-	Host    string `mapstructure:"host"`
-	SnsPort int    `mapstructure:"sns_port"`
-	SqsPort int    `mapstructure:"sqs_port"`
+type SnsSqsTestClients struct {
```
Comment (applike-ss) [inline pkg/test/component_sns_sqs.go]: unused struct?

File: test/component_cloudwatch_test.go (hunk 6 above)
Comment (josketres) [reply test/component_cloudwatch_test.go]: Check the new version. This problem is solved already with the `Clients` approach.

File: pkg/test/component_sns_sqs.go [hunk 23]
```diff
@@ -2,131 +2,95 @@ package test
...
+	Sns *sns.SNS
+	Sqs *sqs.SQS
 }
```
Comment (applike-ss) [inline pkg/test/component_sns_sqs.go]: Please also remove the OnDestroy func() in docker.go

Comment (josketres) [reply pkg/test/component_sns_sqs.go]: ✅

File: pkg/test/component_sns_sqs.go (hunk 22 above)
Comment (josketres) [reply pkg/test/component_sns_sqs.go]: ✅

File: pkg/test/component_kinesis.go (hunk 21 above)
Comment (josketres) [reply pkg/test/component_kinesis.go]: I will panic in the getAwsSession function instead

✅

File: pkg/test/component_cloudwatch.go (hunk 20 above)
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: ✅

File: pkg/test/component_cloudwatch.go (hunk 19 above)
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: Yes we are. See dockerRunner.
✅

File: test/component_cloudwatch_test.go (hunk 18 above)
Comment (josketres) [reply test/component_cloudwatch_test.go]: I'll refactor this as discussed.

File: go.mod (hunk 17 above)
Comment (josketres) [reply go.mod]: We have 2 
```bash
grep uuid go.mod | grep -v indirect
```
