### PR TITLE
test: fixes health checks for components, sometimes there is an issue…

### LINKED ISSUE #176: fix: test-component based integration tests fail sometimes
See example: https://github.com/applike/gosoline/runs/453035977

Investigate why this is happening and fix it.

### PR DESCRIPTION
**Pull request by josketres**
… because components are not ready yet;

Closes #176 

**Summary:**

- Consistent caching of provided clients.
- Use of a generic healthcheck for LocalStack based components.
- Add debug option to print out docker container logs.
- Stabilise health checks for all components.
- Use of executor for sql/sns based tests (LocalStack is not stable enough).
- Remove old DynamoDB fixtures logic.

**Next steps:**
- Cleanup and generalise host discovery.

### CODE REVIEW

File: pkg/test/component_redis.go [hunk 1]
```diff
@@ -4,14 +4,33 @@ import (
...
+	redisConfigs = make(map[string]*redisConfig)
+}
+
+func ProvideRedisClient(name string) *redis.Client {
+	return redisClients.New(name, func() interface{} {
+		addr := fmt.Sprintf("%s:%d", redisConfigs[name].Host, redisConfigs[name].Port)
+
+		return redis.NewClient(&redis.Options{
+			Addr:     addr,
+			Password: "", // no password set
```
Comment (applike-ss) [inline pkg/test/component_redis.go]: i don't think we need the comments here

File: pkg/test/component_redis.go [hunk 2]
```diff
@@ -4,14 +4,33 @@ import (
...
 
+var redisConfigs map[string]*redisConfig
+var redisClients simpleCache
+
+func init() {
+	redisClients = simpleCache{}
+	redisConfigs = make(map[string]*redisConfig)
+}
+
+func ProvideRedisClient(name string) *redis.Client {
```
Comment (applike-ss) [inline pkg/test/component_redis.go]: i would suggest to put the functions in execution order

File: pkg/test/component_sns_sqs.go [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+var snsSqsConfigs map[string]*snsSqsConfig
+
+var localstackClients = simpleCache{}
+
+func init() {
+	snsSqsConfigs = map[string]*snsSqsConfig{}
+	localstackClients = simpleCache{}
+}
+
+// do we really need this ?
```
Comment (applike-ss) [inline pkg/test/component_sns_sqs.go]: i think we should keep it. This ensures that between two tests containers with the same name but different ips get the proper client

File: pkg/test/component_sns_sqs.go [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+		"sqs",
+	}, ",")
+
+	env := []string{services}
+
+	if localConfig.Debug {
+		env = append(env, "DEBUG=1")
+	}
+
+	runContainer("gosoline_test_sns_sqs", ContainerConfig{
```
Comment (applike-ss) [inline pkg/test/component_sns_sqs.go]: also here i would like to see a const for the container name string

File: pkg/test/test.go [hunk 5]
```diff
@@ -5,23 +5,30 @@ import (
...
 	dockerPool, err = dockertest.NewPool("")
+	dockerPool.MaxWait = 2 * time.Minute
 	dockerResources = make([]*dockertest.Resource, 0)
 
 	if err != nil {
 		log.Fatalf("Could not connect to docker: %s", err)
 	}
 }
 
+func Pool() *dockertest.Pool {
```
Comment (applike-ss) [inline pkg/test/test.go]: this is a dead test function that can be removed

File: pkg/test/test.go [hunk 6]
```diff
@@ -38,22 +45,23 @@ func Boot(configFilenames ...string) {
 		bootFromFile(filename)
 	}
 
-	wait.Wait()
```
Comment (applike-ss) [inline pkg/test/test.go]: i think we can re-add this and remove the implementation at the bottom where we wait for each mock individually. This should then increase the overall speed

File: test/test_configs/config.sqs.test.yml [hunk 7]
```diff
@@ -1,5 +1,6 @@
 mocks:
-  sqs:
-    component: sqs
+  - name: sns_sqs
```
Comment (applike-ss) [inline test/test_configs/config.sqs.test.yml]: i think we can remove this complete file and let the sqs test use the sns_sqs test config

File: test/component_sns_sqs_test.go [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+		CancelDelay:         time.Second * 1,
+		InitialInterval:     time.Millisecond * 50,
+		RandomizationFactor: 0.5,
+		Multiplier:          1.5,
+		MaxInterval:         time.Second * 10,
+		MaxElapsedTime:      time.Minute * 2,
+	})
+
+	// create a topic
+	_, err := executor.Execute(context.Background(), func() (request *request.Request, i interface{}) {
```
Comment (applike-ss) [inline test/component_sns_sqs_test.go]:
```suggestion
	_, err := executor.Execute(context.Background(), func() (_ *request.Request, _ interface{}) {
```

File: pkg/test/test.go (hunk 5 above)
Comment (josketres) [reply pkg/test/test.go]: ✅

File: pkg/test/cache.go [hunk 9]
```diff
@@ -0,0 +1,23 @@
+package test
+
+import "sync"
+
+type simpleCache struct {
+	lock  sync.Mutex
+	cache map[string]interface{}
+}
+
+func (c *simpleCache) New(name string, factory func() interface{}) interface{} {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/cache.go]: tried it, but decided to keep it as it is because it is less boilerplate.

File: pkg/test/component_cloudwatch.go [hunk 10]
```diff
@@ -4,41 +4,32 @@ import (
...
-	defer cloudwatchLck.Unlock()
+	return cloudwatchClients.New(name, func() interface{} {
+		sess, err := getSession(cloudwatchConfigs[name].Host, cloudwatchConfigs[name].Port)
 
-	_, ok := cloudwatchClients[name]
-	if ok {
-		return cloudwatchClients[name]
-	}
+		if err != nil {
+			logErr(err, "could not create cloudwatch client: %s")
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: ✅

File: pkg/test/component_cloudwatch.go [hunk 11]
```diff
@@ -56,18 +47,14 @@ func doRunCloudwatch(name string, configMap configInput) {
 
 	runContainer("gosoline_test_cloudwatch", ContainerConfig{
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_cloudwatch.go]: ✅

File: pkg/test/component_dynamodb.go [hunk 12]
```diff
@@ -66,26 +52,10 @@ func doRunDynamoDb(name string, configMap configInput) {
...
-	}
-
-	for tablename, fixture := range fixtures {
-		createDynamoDbTable(name, tablename, fixture)
-	}
+	runDynamoDbContainer(name, config)
 }
 
-func runDynamoDbContainer(name string) {
+func runDynamoDbContainer(name string, config *dynamoDbConfig) {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_dynamodb.go]: ✅

File: pkg/test/component_kinesis.go [hunk 13]
```diff
@@ -4,41 +4,34 @@ import (
...
 func init() {
 	kinesisConfigs = map[string]*kinesisConfig{}
-	kinesisClients = map[string]*kinesis.Kinesis{}
+	kinesisClients = simpleCache{}
 }
 
 func ProvideKinesisClient(name string) *kinesis.Kinesis {
-	kinesisLck.Lock()
-	defer kinesisLck.Unlock()
+	return kinesisClients.New("", func() interface{} {
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/component_kinesis.go]: ✅

File: pkg/test/component_redis.go (hunk 2 above)
Comment (josketres) [reply pkg/test/component_redis.go]: ✅

File: pkg/test/component_redis.go (hunk 1 above)
Comment (josketres) [reply pkg/test/component_redis.go]: ✅

File: pkg/test/component_sns_sqs.go (hunk 3 above)
Comment (josketres) [reply pkg/test/component_sns_sqs.go]: ✅

File: pkg/test/component_sns_sqs.go (hunk 4 above)
Comment (josketres) [reply pkg/test/component_sns_sqs.go]: ✅

File: pkg/test/test.go (hunk 6 above)
Comment (josketres) [reply pkg/test/test.go]: ✅

File: test/component_sns_sqs_test.go (hunk 8 above)
Comment (josketres) [reply test/component_sns_sqs_test.go]: ✅

File: test/test_configs/config.sqs.test.yml (hunk 7 above)
Comment (josketres) [reply test/test_configs/config.sqs.test.yml]: ✅

File: pkg/test/aws_session.go [hunk 14]
```diff
@@ -2,23 +2,47 @@ package test
...
+		MaxRetries:                    mdl.Int(30),
+		Region:                        aws.String(endpoints.EuCentral1RegionID),
+		Endpoint:                      aws.String(endpoint),
+		HTTPClient:                    httpClient,
+	}
+
+	newSession, err := session.NewSession(config)
+
+	if err != nil {
+		panic(err)
```
[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/aws_session.go]: `defer pkgTest.Shutdown()` will still run after a panic

[the remark this answers is not in the document]
Comment (josketres) [reply pkg/test/aws_session.go]: image
